name: SonarQube Scan

on:
  push:
    branches:
      - main
      - text
  pull_request:
    branches:
      - main
      - text

jobs:
  sonar:
    name: SonarQube Analysis
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # tránh shallow clone để phân tích tốt hơn

- name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
